// Auto-generated by memo-grafter init.
// Do not edit this file manually. Re-run `npx memo-grafter init` to regenerate it.

export const memoGrafterExtensions = [
  {
    "name": "vector",
    "description": "pgvector support for topic and memory embeddings."
  },
  {
    "name": "pgcrypto",
    "description": "UUID generation for MemoGrafter memory and registry rows."
  }
] as const;

export const memoGrafterTables = {
  mg_agent_identities: {
    name: "mg_agent_identities",
    description: "Persistent agent identities within a tenant, independent of fleet workers.",
    columns: {
      tenant_id: {
        name: "tenant_id",
        type: "text",
        primaryKey: true,
      },
      agent_id: {
        name: "agent_id",
        type: "text",
        primaryKey: true,
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
  mg_agent_runs: {
    name: "mg_agent_runs",
    description: "Agent task execution records, distinct from memory ingestion jobs.",
    columns: {
      tenant_id: {
        name: "tenant_id",
        type: "text",
        primaryKey: true,
      },
      run_id: {
        name: "run_id",
        type: "text",
        primaryKey: true,
      },
      agent_id: {
        name: "agent_id",
        type: "text",
      },
      task_id: {
        name: "task_id",
        type: "text",
      },
      objective: {
        name: "objective",
        type: "text",
      },
      session_id: {
        name: "session_id",
        type: "text",
        nullable: true,
      },
      project_id: {
        name: "project_id",
        type: "text",
        nullable: true,
      },
      status: {
        name: "status",
        type: "text",
        default: "'running'",
        check: "status IN ('running','interrupted','succeeded','failed','cancelled')",
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
      updated_at: {
        name: "updated_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["FOREIGN KEY (tenant_id, agent_id) REFERENCES mg_agent_identities(tenant_id, agent_id)"]
  },
  mg_agent_events: {
    name: "mg_agent_events",
    description: "Immutable ordered agent events with retry-safe IDs and original evidence.",
    columns: {
      tenant_id: {
        name: "tenant_id",
        type: "text",
        primaryKey: true,
      },
      run_id: {
        name: "run_id",
        type: "text",
        primaryKey: true,
      },
      event_id: {
        name: "event_id",
        type: "text",
        primaryKey: true,
      },
      sequence: {
        name: "sequence",
        type: "int",
        check: "sequence >= 0",
      },
      event: {
        name: "event",
        type: "jsonb",
        check: "jsonb_typeof(event) = 'object'",
      },
      received_at: {
        name: "received_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["UNIQUE (tenant_id, run_id, sequence)","FOREIGN KEY (tenant_id, run_id) REFERENCES mg_agent_runs(tenant_id, run_id)"]
  },
  mg_topic_clusters: {
    name: "mg_topic_clusters",
    description: "Optional session-scoped topic domains; no retrieval graph edges.",
    columns: {
      id: {
        name: "id",
        type: "uuid",
        primaryKey: true,
        default: "gen_random_uuid()",
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      label: {
        name: "label",
        type: "text",
      },
      normalized_label: {
        name: "normalized_label",
        type: "text",
      },
      aliases: {
        name: "aliases",
        type: "text[]",
        default: "'{}'",
      },
      description: {
        name: "description",
        type: "text",
      },
      embedding: {
        name: "embedding",
        type: "vector",
      },
      revision: {
        name: "revision",
        type: "int",
        default: "1",
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
      updated_at: {
        name: "updated_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["UNIQUE (session_id, normalized_label)","UNIQUE (session_id, id)"]
  },
  mg_message_buffer: {
    name: "mg_message_buffer",
    description: "Ordered raw messages for each MemoGrafter session.",
    columns: {
      session_id: {
        name: "session_id",
        type: "text",
        primaryKey: true,
      },
      message_index: {
        name: "message_index",
        type: "int",
        primaryKey: true,
      },
      role: {
        name: "role",
        type: "text",
      },
      content: {
        name: "content",
        type: "text",
      },
    }
  },
  mg_segments: {
    name: "mg_segments",
    description: "Topic segment ranges detected during ingestion.",
    columns: {
      id: {
        name: "id",
        type: "text",
        primaryKey: true,
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      start_index: {
        name: "start_index",
        type: "int",
      },
      end_index: {
        name: "end_index",
        type: "int",
      },
      topic_order: {
        name: "topic_order",
        type: "int",
      },
      drift_score: {
        name: "drift_score",
        type: "float",
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["UNIQUE (session_id, start_index, end_index)"]
  },
  mg_topic_nodes: {
    name: "mg_topic_nodes",
    description: "Topic-level graph nodes with summaries and embeddings.",
    columns: {
      id: {
        name: "id",
        type: "text",
        primaryKey: true,
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      segment_id: {
        name: "segment_id",
        type: "text",
        references: "mg_segments(id)",
      },
      label: {
        name: "label",
        type: "text",
        nullable: true,
      },
      summary: {
        name: "summary",
        type: "text",
        nullable: true,
      },
      embedding: {
        name: "embedding",
        type: "vector",
        nullable: true,
      },
      tags: {
        name: "tags",
        type: "text[]",
        default: "'{}'",
      },
      source: {
        name: "source",
        type: "text",
        nullable: true,
      },
      message_range: {
        name: "message_range",
        type: "int",
        nullable: true,
      },
      topic_order: {
        name: "topic_order",
        type: "int",
        default: "0",
      },
      drift_score: {
        name: "drift_score",
        type: "float",
        default: "0",
      },
      agent_color: {
        name: "agent_color",
        type: "text",
        nullable: true,
      },
      fleet_id: {
        name: "fleet_id",
        type: "text",
        nullable: true,
      },
      agent_id: {
        name: "agent_id",
        type: "text",
        nullable: true,
      },
      suppressed: {
        name: "suppressed",
        type: "boolean",
        default: "false",
      },
      suppressed_at: {
        name: "suppressed_at",
        type: "timestamptz",
        nullable: true,
      },
      pinned: {
        name: "pinned",
        type: "boolean",
        default: "false",
      },
      pinned_at: {
        name: "pinned_at",
        type: "timestamptz",
        nullable: true,
      },
      cluster_id: {
        name: "cluster_id",
        type: "uuid",
        nullable: true,
      },
      cluster_assignment: {
        name: "cluster_assignment",
        type: "jsonb",
        nullable: true,
      },
      episode_count: {
        name: "episode_count",
        type: "int",
        default: "1",
      },
      embedding_count: {
        name: "embedding_count",
        type: "int",
        default: "1",
      },
      first_active_at: {
        name: "first_active_at",
        type: "timestamptz",
        nullable: true,
      },
      last_active_at: {
        name: "last_active_at",
        type: "timestamptz",
        nullable: true,
      },
      last_episode_id: {
        name: "last_episode_id",
        type: "uuid",
        nullable: true,
      },
      revision: {
        name: "revision",
        type: "int",
        default: "1",
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["UNIQUE (segment_id)","FOREIGN KEY (session_id, cluster_id) REFERENCES mg_topic_clusters(session_id, id) ON DELETE SET NULL (cluster_id)"]
  },
  mg_episodes: {
    name: "mg_episodes",
    description: "Interaction-level history assigned to stable topic nodes.",
    columns: {
      id: {
        name: "id",
        type: "uuid",
        primaryKey: true,
        default: "gen_random_uuid()",
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      segment_id: {
        name: "segment_id",
        type: "text",
        references: "mg_segments(id)",
        unique: true,
      },
      topic_id: {
        name: "topic_id",
        type: "text",
        references: "mg_topic_nodes(id)",
      },
      summary: {
        name: "summary",
        type: "text",
      },
      intent: {
        name: "intent",
        type: "text",
      },
      outcome: {
        name: "outcome",
        type: "text",
      },
      open_question: {
        name: "open_question",
        type: "text",
        nullable: true,
      },
      embedding: {
        name: "embedding",
        type: "vector",
        nullable: true,
      },
      message_range: {
        name: "message_range",
        type: "int[]",
      },
      episode_order: {
        name: "episode_order",
        type: "int",
      },
      source_type: {
        name: "source_type",
        type: "text",
        default: "conversation",
        check: "conversation|note|document|code",
      },
      source: {
        name: "source",
        type: "text",
        nullable: true,
      },
      tags: {
        name: "tags",
        type: "text[]",
        default: "'{}'",
      },
      assignment_method: {
        name: "assignment_method",
        type: "text",
        default: "created",
        check: "created|embedding|llm|backfill",
      },
      assignment_similarity: {
        name: "assignment_similarity",
        type: "float",
        nullable: true,
      },
      assignment_version: {
        name: "assignment_version",
        type: "int",
        default: "1",
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["UNIQUE (session_id, episode_order)"]
  },
  mg_topic_edges: {
    name: "mg_topic_edges",
    description: "Temporal, semantic, reentry, and graft edges between topic nodes.",
    columns: {
      src_id: {
        name: "src_id",
        type: "text",
        primaryKey: true,
      },
      dst_id: {
        name: "dst_id",
        type: "text",
        primaryKey: true,
      },
      weight: {
        name: "weight",
        type: "float",
      },
      type: {
        name: "type",
        type: "text",
      },
    }
  },
  mg_memory_nodes: {
    name: "mg_memory_nodes",
    description: "Structured memory facts extracted from topic segments.",
    columns: {
      id: {
        name: "id",
        type: "uuid",
        primaryKey: true,
        default: "gen_random_uuid()",
      },
      segment_id: {
        name: "segment_id",
        type: "text",
        references: "mg_segments(id)",
      },
      topic_node_id: {
        name: "topic_node_id",
        type: "text",
        references: "mg_topic_nodes(id)",
      },
      agent_id: {
        name: "agent_id",
        type: "text",
        nullable: true,
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      memory_type: {
        name: "memory_type",
        type: "text",
        check: "fact|insight|question|task|reference",
      },
      source_type: {
        name: "source_type",
        type: "text",
        default: "conversation",
        check: "conversation|note|document|code",
      },
      subject: {
        name: "subject",
        type: "text",
      },
      predicate: {
        name: "predicate",
        type: "text",
      },
      value: {
        name: "value",
        type: "text",
      },
      canonical_subject: {
        name: "canonical_subject",
        type: "text",
        nullable: true,
      },
      canonical_predicate: {
        name: "canonical_predicate",
        type: "text",
        nullable: true,
      },
      canonical_value: {
        name: "canonical_value",
        type: "text",
        nullable: true,
      },
      canonical_fact_key: {
        name: "canonical_fact_key",
        type: "text",
        nullable: true,
      },
      canonical_value_key: {
        name: "canonical_value_key",
        type: "text",
        nullable: true,
      },
      canonicalization_version: {
        name: "canonicalization_version",
        type: "int",
        default: "1",
      },
      reinforcement_count: {
        name: "reinforcement_count",
        type: "int",
        default: "1",
      },
      last_reinforced_at: {
        name: "last_reinforced_at",
        type: "timestamptz",
        nullable: true,
      },
      quality_explicitness: {
        name: "quality_explicitness",
        type: "float",
        default: "0.5",
      },
      quality_source_reliability: {
        name: "quality_source_reliability",
        type: "float",
        default: "0.5",
      },
      quality_stability: {
        name: "quality_stability",
        type: "float",
        default: "0.5",
      },
      quality_salience: {
        name: "quality_salience",
        type: "float",
        default: "0.5",
      },
      quality_defaulted: {
        name: "quality_defaulted",
        type: "text[]",
        default: "'{explicitness,sourceReliability,stability,salience}'",
      },
      quality_origin: {
        name: "quality_origin",
        type: "text",
        default: "legacy",
      },
      quality_updated_at: {
        name: "quality_updated_at",
        type: "timestamptz",
        default: "now()",
      },
      embedding: {
        name: "embedding",
        type: "vector",
        nullable: true,
      },
      tags: {
        name: "tags",
        type: "text[]",
        default: "'{}'",
      },
      source: {
        name: "source",
        type: "text",
        nullable: true,
      },
      source_url: {
        name: "source_url",
        type: "text",
        nullable: true,
      },
      source_title: {
        name: "source_title",
        type: "text",
        nullable: true,
      },
      source_spans: {
        name: "source_spans",
        type: "jsonb",
        default: "'[]'::jsonb",
      },
      provenance_speaker: {
        name: "provenance_speaker",
        type: "text",
        nullable: true,
        check: "user|assistant|system|document",
      },
      provenance_message_indexes: {
        name: "provenance_message_indexes",
        type: "int[]",
        nullable: true,
      },
      provenance_session_id: {
        name: "provenance_session_id",
        type: "text",
        nullable: true,
      },
      extraction_method: {
        name: "extraction_method",
        type: "text",
        nullable: true,
        check: "explicit|inferred|user-confirmed|document-extraction",
      },
      superseded_by: {
        name: "superseded_by",
        type: "uuid",
        nullable: true,
        references: "mg_memory_nodes(id)",
      },
      decayed: {
        name: "decayed",
        type: "boolean",
        default: "false",
      },
      forgotten: {
        name: "forgotten",
        type: "boolean",
        default: "false",
      },
      forgotten_at: {
        name: "forgotten_at",
        type: "timestamptz",
        nullable: true,
      },
      has_conflict: {
        name: "has_conflict",
        type: "boolean",
        default: "false",
      },
      agent_color: {
        name: "agent_color",
        type: "text",
        nullable: true,
      },
      fleet_id: {
        name: "fleet_id",
        type: "text",
        nullable: true,
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["CHECK (quality_explicitness >= 0 AND quality_explicitness <= 1)","CHECK (quality_source_reliability >= 0 AND quality_source_reliability <= 1)","CHECK (quality_stability >= 0 AND quality_stability <= 1)","CHECK (quality_salience >= 0 AND quality_salience <= 1)"]
  },
  mg_memory_evidence: {
    name: "mg_memory_evidence",
    description: "Immutable observations supporting canonical memory nodes.",
    columns: {
      id: {
        name: "id",
        type: "uuid",
        primaryKey: true,
        default: "gen_random_uuid()",
      },
      memory_node_id: {
        name: "memory_node_id",
        type: "uuid",
        references: "mg_memory_nodes(id)",
      },
      segment_id: {
        name: "segment_id",
        type: "text",
        references: "mg_segments(id)",
      },
      topic_node_id: {
        name: "topic_node_id",
        type: "text",
        references: "mg_topic_nodes(id)",
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      episode_id: {
        name: "episode_id",
        type: "uuid",
        nullable: true,
        references: "mg_episodes(id)",
      },
      original_subject: {
        name: "original_subject",
        type: "text",
      },
      original_predicate: {
        name: "original_predicate",
        type: "text",
      },
      original_value: {
        name: "original_value",
        type: "text",
      },
      quality_explicitness: {
        name: "quality_explicitness",
        type: "float",
        default: "0.5",
      },
      quality_source_reliability: {
        name: "quality_source_reliability",
        type: "float",
        default: "0.5",
      },
      quality_stability: {
        name: "quality_stability",
        type: "float",
        default: "0.5",
      },
      quality_salience: {
        name: "quality_salience",
        type: "float",
        default: "0.5",
      },
      quality_defaulted: {
        name: "quality_defaulted",
        type: "text[]",
        default: "'{explicitness,sourceReliability,stability,salience}'",
      },
      quality_origin: {
        name: "quality_origin",
        type: "text",
        default: "legacy",
      },
      quality_updated_at: {
        name: "quality_updated_at",
        type: "timestamptz",
        default: "now()",
      },
      source_spans: {
        name: "source_spans",
        type: "jsonb",
        default: "'[]'::jsonb",
      },
      provenance_speaker: {
        name: "provenance_speaker",
        type: "text",
        nullable: true,
      },
      provenance_message_indexes: {
        name: "provenance_message_indexes",
        type: "int[]",
        nullable: true,
      },
      provenance_session_id: {
        name: "provenance_session_id",
        type: "text",
        nullable: true,
      },
      extraction_method: {
        name: "extraction_method",
        type: "text",
        nullable: true,
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["UNIQUE (memory_node_id, segment_id, provenance_message_indexes)","CHECK (quality_explicitness >= 0 AND quality_explicitness <= 1)","CHECK (quality_source_reliability >= 0 AND quality_source_reliability <= 1)","CHECK (quality_stability >= 0 AND quality_stability <= 1)","CHECK (quality_salience >= 0 AND quality_salience <= 1)"]
  },
  mg_memory_edges: {
    name: "mg_memory_edges",
    description: "Semantic, conflict, update, and related edges between memory facts.",
    columns: {
      id: {
        name: "id",
        type: "uuid",
        primaryKey: true,
        default: "gen_random_uuid()",
      },
      source_id: {
        name: "source_id",
        type: "uuid",
        references: "mg_memory_nodes(id)",
      },
      target_id: {
        name: "target_id",
        type: "uuid",
        references: "mg_memory_nodes(id)",
      },
      edge_type: {
        name: "edge_type",
        type: "text",
        check: "semantic|conflicts|updates|related",
      },
      weight: {
        name: "weight",
        type: "float",
        nullable: true,
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
  mg_fleets: {
    name: "mg_fleets",
    description: "Fleet metadata for multi-agent memory groups.",
    columns: {
      id: {
        name: "id",
        type: "text",
        primaryKey: true,
      },
      name: {
        name: "name",
        type: "text",
        nullable: true,
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
  mg_fleet_agents: {
    name: "mg_fleet_agents",
    description: "Registered worker agents within fleets.",
    columns: {
      id: {
        name: "id",
        type: "text",
        primaryKey: true,
      },
      fleet_id: {
        name: "fleet_id",
        type: "text",
        references: "mg_fleets(id)",
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      agent_color: {
        name: "agent_color",
        type: "text",
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["UNIQUE (fleet_id, agent_color)"]
  },
  mg_sessions: {
    name: "mg_sessions",
    description: "Human-friendly metadata for MemoGrafter sessions.",
    columns: {
      session_id: {
        name: "session_id",
        type: "text",
        primaryKey: true,
      },
      label: {
        name: "label",
        type: "text",
        nullable: true,
      },
      description: {
        name: "description",
        type: "text",
        nullable: true,
      },
      tags: {
        name: "tags",
        type: "text[]",
        default: "'{}'",
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
      updated_at: {
        name: "updated_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
  mg_session_ingest_state: {
    name: "mg_session_ingest_state",
    description: "Incremental ingestion checkpoints by session.",
    columns: {
      session_id: {
        name: "session_id",
        type: "text",
        primaryKey: true,
      },
      last_ingested_message_index: {
        name: "last_ingested_message_index",
        type: "int",
        default: "-1",
      },
      updated_at: {
        name: "updated_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
  mg_ingestion_runs: {
    name: "mg_ingestion_runs",
    description: "Durable lifecycle and retry state for accepted ingestion ranges.",
    columns: {
      document_payload: {
        name: "document_payload",
        type: "jsonb",
        nullable: true,
      },
      prepared_payload: {
        name: "prepared_payload",
        type: "jsonb",
        nullable: true,
      },
      result_payload: {
        name: "result_payload",
        type: "jsonb",
        nullable: true,
      },
      cancel_requested_at: {
        name: "cancel_requested_at",
        type: "timestamptz",
        nullable: true,
      },
      superseded_at: {
        name: "superseded_at",
        type: "timestamptz",
        nullable: true,
      },
      id: {
        name: "id",
        type: "uuid",
        primaryKey: true,
        default: "gen_random_uuid()",
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      kind: {
        name: "kind",
        type: "text",
      },
      start_index: {
        name: "start_index",
        type: "int",
      },
      end_index: {
        name: "end_index",
        type: "int",
      },
      idempotency_key: {
        name: "idempotency_key",
        type: "text",
        nullable: true,
      },
      status: {
        name: "status",
        type: "text",
      },
      attempt_count: {
        name: "attempt_count",
        type: "int",
        default: "0",
      },
      queued_at: {
        name: "queued_at",
        type: "timestamptz",
        nullable: true,
      },
      started_at: {
        name: "started_at",
        type: "timestamptz",
        nullable: true,
      },
      completed_at: {
        name: "completed_at",
        type: "timestamptz",
        nullable: true,
      },
      failed_at: {
        name: "failed_at",
        type: "timestamptz",
        nullable: true,
      },
      lease_expires_at: {
        name: "lease_expires_at",
        type: "timestamptz",
        nullable: true,
      },
      heartbeat_at: {
        name: "heartbeat_at",
        type: "timestamptz",
        nullable: true,
      },
      last_error_code: {
        name: "last_error_code",
        type: "text",
        nullable: true,
      },
      last_error_stage: {
        name: "last_error_stage",
        type: "text",
        nullable: true,
      },
      last_error_safe_message: {
        name: "last_error_safe_message",
        type: "text",
        nullable: true,
      },
      retryable: {
        name: "retryable",
        type: "boolean",
        nullable: true,
      },
      worker_id: {
        name: "worker_id",
        type: "text",
        nullable: true,
      },
      created_at: {
        name: "created_at",
        type: "timestamptz",
        default: "now()",
      },
      updated_at: {
        name: "updated_at",
        type: "timestamptz",
        default: "now()",
      },
    },
    constraints: ["CHECK (start_index >= 0)","CHECK (end_index >= start_index)"]
  },
  mg_graft_registry: {
    name: "mg_graft_registry",
    description: "Tracks copied/grafted topic node origins.",
    columns: {
      id: {
        name: "id",
        type: "uuid",
        primaryKey: true,
        default: "gen_random_uuid()",
      },
      session_id: {
        name: "session_id",
        type: "text",
      },
      node_id: {
        name: "node_id",
        type: "text",
        references: "mg_topic_nodes(id)",
      },
      source_session_id: {
        name: "source_session_id",
        type: "text",
      },
      source_node_id: {
        name: "source_node_id",
        type: "text",
      },
      grafted_at: {
        name: "grafted_at",
        type: "timestamptz",
        default: "now()",
      },
    }
  },
} as const;

export const memoGrafterIndexes = [
  {
    "name": "mg_ingestion_runs_current_message_range_idx",
    "table": "mg_ingestion_runs",
    "description": "Unique current message ranges; documents stage independently."
  },
  {
    "name": "mg_agent_events_tool_idx",
    "table": "mg_agent_events",
    "description": "Unique tool-call/result correlation within a run."
  },
  {
    "name": "mg_agent_runs_owner_idx",
    "table": "mg_agent_runs",
    "description": "Runs by tenant and owning agent."
  },
  {
    "name": "mg_agent_runs_project_idx",
    "table": "mg_agent_runs",
    "description": "Project-shared runs within a tenant."
  },
  {
    "name": "idx_topic_nodes_cluster",
    "table": "mg_topic_nodes",
    "description": "Session-scoped cluster membership lookup."
  },
  {
    "name": "mg_message_buffer_session_idx",
    "table": "mg_message_buffer",
    "description": "Message lookup by session and index."
  },
  {
    "name": "mg_segments_session_idx",
    "table": "mg_segments",
    "description": "Segment lookup by session and topic order."
  },
  {
    "name": "mg_nodes_session_idx",
    "table": "mg_topic_nodes",
    "description": "Topic lookup by session and topic order."
  },
  {
    "name": "idx_topic_nodes_active_lifecycle",
    "table": "mg_topic_nodes",
    "description": "Active topic lifecycle lookup."
  },
  {
    "name": "mg_topic_nodes_pinned_idx",
    "table": "mg_topic_nodes",
    "description": "Ordered pinned-topic lookup by session."
  },
  {
    "name": "mg_topic_nodes_tags_idx",
    "table": "mg_topic_nodes",
    "description": "Topic tag lookup."
  },
  {
    "name": "mg_nodes_fleet_idx",
    "table": "mg_topic_nodes",
    "description": "Fleet topic lookup by color."
  },
  {
    "name": "mg_fleet_agents_fleet_idx",
    "table": "mg_fleet_agents",
    "description": "Fleet agent lookup by color."
  },
  {
    "name": "mg_sessions_label_lower_idx",
    "table": "mg_sessions",
    "description": "Case-insensitive session label lookup."
  },
  {
    "name": "mg_session_ingest_state_updated_idx",
    "table": "mg_session_ingest_state",
    "description": "Ingest state freshness lookup."
  },
  {
    "name": "mg_ingestion_runs_session_status_idx",
    "table": "mg_ingestion_runs",
    "description": "Ingestion status lookup by session."
  },
  {
    "name": "mg_ingestion_runs_idempotency_idx",
    "table": "mg_ingestion_runs",
    "description": "Caller idempotency key uniqueness by session."
  },
  {
    "name": "mg_ingestion_runs_pending_idx",
    "table": "mg_ingestion_runs",
    "description": "Pending and retryable ingestion lookup."
  },
  {
    "name": "mg_ingestion_runs_lease_idx",
    "table": "mg_ingestion_runs",
    "description": "Expired worker lease lookup."
  },
  {
    "name": "idx_graft_registry_session",
    "table": "mg_graft_registry",
    "description": "Graft registry lookup by session."
  },
  {
    "name": "idx_graft_registry_node_unique",
    "table": "mg_graft_registry",
    "description": "Unique graft registry node ownership."
  },
  {
    "name": "idx_graft_registry_source_target_unique",
    "table": "mg_graft_registry",
    "description": "Prevents duplicate source-topic grafts into a target session."
  },
  {
    "name": "idx_graft_registry_source",
    "table": "mg_graft_registry",
    "description": "Source topic provenance lookup."
  },
  {
    "name": "mg_nodes_embedding_idx",
    "table": "mg_topic_nodes",
    "description": "Topic vector similarity search."
  },
  {
    "name": "idx_topic_nodes_activity",
    "table": "mg_topic_nodes",
    "description": "Stable-topic activity lookup."
  },
  {
    "name": "idx_episodes_session_order",
    "table": "mg_episodes",
    "description": "Episode chronology within a session."
  },
  {
    "name": "idx_episodes_topic_activity",
    "table": "mg_episodes",
    "description": "Recent episodes for a topic."
  },
  {
    "name": "idx_episodes_embedding_hnsw",
    "table": "mg_episodes",
    "description": "Episode vector similarity search."
  },
  {
    "name": "idx_memory_nodes_topic",
    "table": "mg_memory_nodes",
    "description": "Memory lookup by topic node."
  },
  {
    "name": "idx_memory_nodes_segment",
    "table": "mg_memory_nodes",
    "description": "Memory lookup by segment."
  },
  {
    "name": "idx_memory_nodes_session",
    "table": "mg_memory_nodes",
    "description": "Memory lookup by session."
  },
  {
    "name": "idx_memory_nodes_canonical_fact",
    "table": "mg_memory_nodes",
    "description": "Canonical fact lookup during ingestion."
  },
  {
    "name": "idx_memory_nodes_canonical_value",
    "table": "mg_memory_nodes",
    "description": "Canonical value deduplication during ingestion."
  },
  {
    "name": "idx_memory_evidence_memory",
    "table": "mg_memory_evidence",
    "description": "Evidence lookup by memory."
  },
  {
    "name": "idx_memory_nodes_active_lifecycle",
    "table": "mg_memory_nodes",
    "description": "Active memory lifecycle lookup."
  },
  {
    "name": "idx_memory_nodes_tags",
    "table": "mg_memory_nodes",
    "description": "Memory tag lookup."
  },
  {
    "name": "idx_memory_nodes_embedding",
    "table": "mg_memory_nodes",
    "description": "Memory vector similarity search."
  },
  {
    "name": "idx_memory_edges_source",
    "table": "mg_memory_edges",
    "description": "Memory edge lookup by source."
  },
  {
    "name": "idx_memory_edges_target",
    "table": "mg_memory_edges",
    "description": "Memory edge lookup by target."
  }
] as const;
