import { BookOpen, Download, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import type { MindBloomDocument, NotionPageSummary } from "@mindbloom/shared";
import { importNotionPages, listNotionDocuments, listNotionPages } from "../lib/api";

export function NotionPage() {
  const [pages,setPages]=useState<NotionPageSummary[]>([]); const [documents,setDocuments]=useState<MindBloomDocument[]>([]);
  const [selected,setSelected]=useState<string[]>([]); const [loading,setLoading]=useState(true); const [importing,setImporting]=useState(false); const [error,setError]=useState<string|null>(null);
  async function load() { setLoading(true); setError(null); try { const [p,d]=await Promise.all([listNotionPages(),listNotionDocuments()]); setPages(p.pages); setDocuments(d.documents); } catch(e){setError(e instanceof Error?e.message:"Could not load Notion");} finally {setLoading(false);} }
  useEffect(()=>{void load();},[]);
  async function runImport(){setImporting(true);setError(null);try{const result=await importNotionPages(selected);const failed=result.results.filter(x=>x.status==="failed");setSelected([]);await load();if(failed.length)setError(`${failed.length} page${failed.length===1?"":"s"} could not be imported: ${failed[0]?.error}`);}catch(e){setError(e instanceof Error?e.message:"Import failed");}finally{setImporting(false);}}
  return <main className="mx-auto min-h-dvh w-full max-w-[1120px] px-4 pb-24 pt-6 md:px-8 md:pb-8">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="label-text">Integration</p><h1 className="mt-1 font-serif text-[32px]">Notion garden</h1><p className="mt-2 max-w-2xl text-[13px] leading-5 text-bloom-text-secondary">Choose pages MindBloom may remember. Each imported page becomes its own private thought graph.</p></div><button onClick={()=>void load()} disabled={loading} className="grid h-10 w-10 place-items-center rounded-full border border-bloom-border bg-bloom-surface"><RefreshCw className="h-4 w-4"/></button></header>
    {error?<div className="mt-5 rounded-bloom border border-coral-border bg-coral-bg p-4 text-[13px] text-coral-text">{error}</div>:null}
    <section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="font-serif text-[21px]">Imported pages</h2><span className="text-[12px] text-bloom-text-tertiary">{documents.length} pages</span></div><div className="grid gap-3 md:grid-cols-2">{documents.map(doc=><Link key={doc.id} to={`/notion/${doc.id}`} className="rounded-bloom border border-bloom-border bg-bloom-surface p-4 transition-colors hover:border-bloom-border-mid"><div className="flex items-center gap-2"><BookOpen className="h-4 w-4 text-bloom-accent"/><h3 className="font-medium">{doc.title}</h3></div><p className="mt-2 line-clamp-2 text-[12px] leading-5 text-bloom-text-secondary">{doc.content||"This page has no text blocks."}</p><p className="mt-3 text-[11px] text-bloom-text-tertiary">{doc.status} · synced {doc.lastSyncedAt?new Date(doc.lastSyncedAt).toLocaleString():"never"}</p></Link>)}</div>{!loading&&!documents.length?<p className="rounded-bloom border border-dashed border-bloom-border p-8 text-center text-[13px] text-bloom-text-secondary">No pages imported yet.</p>:null}</section>
    <section className="mt-8"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-serif text-[21px]">Pages shared with MindBloom</h2><p className="text-[12px] text-bloom-text-tertiary">Only pages shared with your internal Notion integration appear here.</p></div><button onClick={()=>void runImport()} disabled={!selected.length||importing} className="flex h-10 items-center gap-2 rounded-bloom-sm bg-bloom-accent px-4 text-[13px] font-medium text-bloom-on-accent disabled:opacity-40"><Download className="h-4 w-4"/>{importing?"Importing…":`Import ${selected.length||"selected"}`}</button></div><div className="divide-y divide-bloom-border rounded-bloom border border-bloom-border bg-bloom-surface">{pages.map(page=><label key={page.id} className="flex cursor-pointer items-center gap-3 p-4"><input type="checkbox" disabled={Boolean(page.importedDocumentId)} checked={selected.includes(page.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,page.id]:current.filter(id=>id!==page.id))}/><span className="min-w-0 flex-1"><span className="block truncate text-[13px] font-medium">{page.title}</span><span className="text-[11px] text-bloom-text-tertiary">Edited {new Date(page.updatedAt).toLocaleDateString()}</span></span>{page.importedDocumentId?<span className="text-[11px] text-bloom-accent">Imported</span>:null}</label>)}</div>{loading?<p className="py-8 text-center text-[13px] text-bloom-text-secondary">Reading your Notion workspace…</p>:null}</section>
  </main>;
}
